
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.RadioButton fullRadio;

	private global::Gtk.RadioButton partRadio;

	private global::Gtk.Entry firstEntry;

	private global::Gtk.Label label1;

	private global::Gtk.Entry lastEntry;

	private global::Gtk.Label label2;

	private global::Gtk.Entry salaryEntry;

	private global::Gtk.Label label3;

	private global::Gtk.Button saveBtn;

	private global::Gtk.Button clearBtn;

	private global::Gtk.Entry messageEntry;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Employee Entry Form");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.fullRadio = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Full Time"));
		this.fullRadio.CanFocus = true;
		this.fullRadio.Name = "fullRadio";
		this.fullRadio.DrawIndicator = true;
		this.fullRadio.UseUnderline = true;
		this.fullRadio.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.fullRadio);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.fullRadio]));
		w1.X = 257;
		w1.Y = 217;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.partRadio = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Part Time"));
		this.partRadio.CanFocus = true;
		this.partRadio.Name = "partRadio";
		this.partRadio.DrawIndicator = true;
		this.partRadio.UseUnderline = true;
		this.partRadio.Group = this.fullRadio.Group;
		this.fixed1.Add(this.partRadio);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.partRadio]));
		w2.X = 257;
		w2.Y = 247;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.firstEntry = new global::Gtk.Entry();
		this.firstEntry.CanFocus = true;
		this.firstEntry.Name = "firstEntry";
		this.firstEntry.IsEditable = true;
		this.firstEntry.InvisibleChar = '•';
		this.fixed1.Add(this.firstEntry);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.firstEntry]));
		w3.X = 151;
		w3.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("First Name");
		this.label1.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w4.X = 51;
		w4.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lastEntry = new global::Gtk.Entry();
		this.lastEntry.CanFocus = true;
		this.lastEntry.Name = "lastEntry";
		this.lastEntry.IsEditable = true;
		this.lastEntry.InvisibleChar = '•';
		this.fixed1.Add(this.lastEntry);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lastEntry]));
		w5.X = 151;
		w5.Y = 57;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Last Name");
		this.label2.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w6.X = 51;
		w6.Y = 66;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.salaryEntry = new global::Gtk.Entry();
		this.salaryEntry.CanFocus = true;
		this.salaryEntry.Name = "salaryEntry";
		this.salaryEntry.IsEditable = true;
		this.salaryEntry.InvisibleChar = '•';
		this.fixed1.Add(this.salaryEntry);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.salaryEntry]));
		w7.X = 151;
		w7.Y = 108;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Salary");
		this.label3.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w8.X = 51;
		w8.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.saveBtn = new global::Gtk.Button();
		this.saveBtn.CanFocus = true;
		this.saveBtn.Name = "saveBtn";
		this.saveBtn.UseUnderline = true;
		this.saveBtn.Label = global::Mono.Unix.Catalog.GetString("Save/Update");
		this.fixed1.Add(this.saveBtn);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.saveBtn]));
		w9.X = 8;
		w9.Y = 177;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.clearBtn = new global::Gtk.Button();
		this.clearBtn.CanFocus = true;
		this.clearBtn.Name = "clearBtn";
		this.clearBtn.UseUnderline = true;
		this.clearBtn.Label = global::Mono.Unix.Catalog.GetString("Cancel");
		this.fixed1.Add(this.clearBtn);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.clearBtn]));
		w10.X = 145;
		w10.Y = 177;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.messageEntry = new global::Gtk.Entry();
		this.messageEntry.WidthRequest = 200;
		this.messageEntry.CanFocus = true;
		this.messageEntry.Name = "messageEntry";
		this.messageEntry.IsEditable = false;
		this.messageEntry.InvisibleChar = '•';
		this.fixed1.Add(this.messageEntry);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.messageEntry]));
		w11.X = 12;
		w11.Y = 267;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 326;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.saveBtn.Clicked += new global::System.EventHandler(this.OnSaveBtnClicked);
		this.clearBtn.Clicked += new global::System.EventHandler(this.OnClearBtnClicked);
	}
}
